-- AlterTable
ALTER TABLE `Task` ADD COLUMN `description` VARCHAR(191) NULL,
    ADD COLUMN `dueDate` DATETIME(3) NULL,
    ADD COLUMN `priority` INTEGER NOT NULL DEFAULT 2,
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'todo',
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
